### PR TITLE
Fix byte compiler warnings

### PR DESCRIPTION
**Pull request by jabranham**

### CODE REVIEW

**Comment by tarsius** [comment]
That's not quite sufficient. Here's how to do it: 9579f0f251a6f13a52fca045de57656542646c61.
I also performed some other cleanup.

**Comment by jabranham** [comment]
Thanks, just updated. However, the bullets for level 3 headings aren't showing up for me anymore.

**Comment by tarsius** [comment]
This appears to be a recent regression in `org` that is unrelated to `org-bullets`.

Given a file with contents:

```
* a
** b
*** c
```

after enabling `org-mode` I see:

```
* a
** b
* c
```

**Comment by jabranham** [comment]
Ah, I see that they just pushed a fix for this on the maint branch. Thanks!

**Pull request closed without merging**
